development:
  adapter: postgresql
  encoding: unicode
  database: Hi5_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: Hi5_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: Hi5_production
  pool: 5
  timeout: 5000
